global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'cadvisor_dev'
    static_configs:
      - targets: ['cadvisor_dev:8080']
  - job_name: 'cadvisor_a'
    static_configs:
      - targets: ['node_a:8081']
  - job_name: 'cadvisor_b'
    static_configs:
      - targets: ['node_b:8081']
