---
services:
  echo:
    image: mendhak/http-https-echo
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - simnet

networks:
  simnet:
    name: simnet
    driver: bridge
