 # Docker Compose configuration for simulating ANYbotics deployment
 # Includes dev container and two Ubuntu-based nodes in a shared network
---
name: anybotics-sim

services:
  dev:
    container_name: dev
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    working_dir: /workspace
    volumes:
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    restart: unless-stopped
    networks:
      - simnet

  node_a:
    container_name: node_a
    image: ubuntu:24.04
    command: sleep infinity
    tty: true
    privileged: true
    restart: unless-stopped
    networks:
      - simnet

  node_b:
    container_name: node_b
    image: ubuntu:24.04
    command: sleep infinity
    tty: true
    privileged: true
    restart: unless-stopped
    networks:
      - simnet

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./docker/dev/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - simnet

  cadvisor_dev:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    networks:
      - simnet

networks:
  simnet:
    driver: bridge
