---
# Deploy echo server on node_b using Docker Compose
# Copies the Compose file and starts the container
- name: Deploy echo server on node_b
  block:
    - name: Copy docker-compose to node_b
      copy:
        src: docker-compose-node_b.yml
        dest: /opt/docker-compose.yml
    - name: Start echo server container with Docker Compose
      command: docker compose -f /opt/docker-compose.yml up -d
  when: inventory_hostname == 'node_b'

# Deploy nginx on node_a using Docker Compose
# Includes copying the Compose and Nginx config, then starting the container
# Includes End-to-End test checking if services are reachable
- name: Deploy nginx on node_a
  block:
    - name: Copy docker-compose to node_a
      copy:
        src: docker-compose-node_a.yml
        dest: /opt/docker-compose.yml

    - name: Copy nginx configuration
      copy:
        src: nginx.conf
        dest: /opt/nginx.conf

    - name: Start nginx container with Docker Compose
      community.docker.docker_compose_v2:
        project_src: /opt
        files:
          - docker-compose.yml
        state: present

    - name: Test if echo service on node_b is reachable
      uri:
        url: http://node_b:8080
        return_content: true
      register: echo_check
      failed_when: echo_check.status != 200

    - name: Output echo service response for debugging
      debug:
        var: echo_check

    - name: Test if echo service is reachable via nginx
      uri:
        url: http://localhost:80
        return_content: true
      register: nginx_check
      failed_when: nginx_check.status != 200

    - name: Output nginx service response for debugging
      debug:
        var: nginx_check

  when: inventory_hostname == 'node_a'
