---
# Install Python using raw module because
# Ansible modules require Python on the target
- name: Install Python (required for Ansible)
  raw: apt-get update && apt-get install -y python3

# Download Docker install script from official source
- name: Download Docker install script
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '0755'

# Run the Docker install script
- name: Run Docker install script
  command: sh /tmp/get-docker.sh

# nohup used since containers lack systemd;
# dockerd must stay alive after provisioning
# Start Docker daemon on node_b with TCP access
# to allow remote control from node_a
- name: Start Docker daemon with TCP (for node_b)
  shell: >
    nohup dockerd -H unix:///var/run/docker.sock
    -H tcp://0.0.0.0:2375 > /var/log/dockerd.log 2>&1 &
  args:
    creates: /var/run/docker.sock
  when: inventory_hostname == 'node_b'

# Start Docker daemon normally on other nodes
- name: Start Docker daemon (default)
  shell: >
    nohup dockerd > /var/log/dockerd.log 2>&1 &
  args:
    creates: /var/run/docker.sock
  when: inventory_hostname != 'node_b'

# Wait until Docker socket is available (daemon is ready)
- name: Wait for Docker socket to become available
  wait_for:
    path: /var/run/docker.sock
    timeout: 30

# Run docker version to ensure Docker is running correctly
- name: Verify Docker is running
  command: docker version
  register: docker_output
  failed_when: docker_output.rc != 0

# Output Docker version information for verification
- name: Show Docker version info
  debug:
    var: docker_output.stdout_lines

# From node_a, test access to Docker API on node_b via TCP (controller test)
- block:
    - name: Check if Node A can reach Docker API on Node B
      uri:
        url: http://node_b:2375/version
        method: GET
        return_content: true
      delegate_to: node_a
      register: docker_remote_check
      failed_when: docker_remote_check.status != 200

    - name: Show remote Docker version (controller test)
      debug:
        var: docker_remote_check.json
  when: inventory_hostname == 'node_a'
